src/app/[locale]/list/_components/AasList.tsx
src/app/[locale]/list/_components/AasListDataWrapper.tsx
src/app/[locale]/list/_components/AasListHeader.tsx
src/app/[locale]/list/_components/AasListTableRow.tsx
src/app/[locale]/list/_components/filter/SelectRepository.tsx
src/components/basics/StyledImageWithFallBack.tsx
src/locale/de.json
src/locale/en.json

Adds Basic Pagination to the new AAS List.

Feat(aas list) pagination

---

src/lib/api/infrastructure.ts

MNES-1378
Fixed Problem, when authentication is not used that you can not delete submodel templates and also not use the id creation settings. Every call now has a API Key if there is no authentication.
-   [ …

fix(Authentication): Fix using TemplateBuilder and Settings, when Authentication is disabled

---

package.json

Quick cleanup of the yarn commands.
- The keycloak service was not pruned with the prune command.
- Removed the -d detached flag like in all other commands. You can manually add it by calling `yarn docker:keycloak -d`. 

chore(yarn): update yarn commands

---

src/user-plugins/submodels/README.md

With this PR we propose a structure for user-plugins. For now these will be custom submodel visualizations.
We have a `user-plugins` directory directly in `src`.
This is found more easily than somewhere in `src/app/[locale]/viewer/_components/submodel`.
This directory can later also be used for custom dashboard components etc.
Should we keep the mnestix components in the nested folder? I think it is ok to leave them for now.
You can clone another project directly into the `user-plugins/submodels` folder and the two git projects are kept separate.
Meaning you can easily update mnestix without interfering with the custom visualizations and you can also commit to the inner project without pushing to mnestix.
For now you will need to touch the mapping files.
Should we move them to be …

refactor(submodel-visualizations): use user-plugins directory for custom visualizations

---

src/app/[locale]/viewer/_components/submodel/SubmodelVisualizationProps.ts
src/app/[locale]/viewer/_components/submodel/bill-of-applications/BillOfApplicationsDetail.tsx
src/app/[locale]/viewer/_components/submodel/carbon-footprint/CarbonFootprintDetail.tsx
src/app/[locale]/viewer/_components/submodel/carbon-footprint/CarbonFootprintVisualizations.tsx
src/app/[locale]/viewer/_components/submodel/generic-submodel/GenericSubmodelDetailComponent.tsx
src/app/[locale]/viewer/_components/submodel/hierarchical-structures/HierarchicalStructuresDetail.tsx
src/app/[locale]/viewer/_components/submodel/reference-counter/ReferenceCounterDetail.tsx
src/app/[locale]/viewer/_components/submodel/reference-counter/ReferenceCounterVisualizations.tsx
src/app/[locale]/viewer/_components/submodel/time-series/TimeSeriesDetail.tsx
src/app/[locale]/viewer/_components/submodel/time-series/TimeSeriesVisualizations.tsx
src/components/basics/ExpandableNestedContentWrapper.tsx

The interface for custom submodel visualizations should be standartized and extendable in the future.
With the approach in this PR we use one type (`SubmodelVisualizationProps`) in every visualization we have for now.
If we need to add a variable to the props in the future, we would be backwards compatible, as the components would just ignore the new properties.
Fixes # (MNES-1422) …

Refactor(submodel visualizations) all existing visualizations use the same props

---

src/global.d.ts
src/lib/hooks/UseShowError.tsx
src/lib/util/LocalizedError.ts

This allows LocalizedError to use any message key as their descriptor.
This needs to be adjusted in every usecase of LocalizedError ;/

allow generic translations in LocalizedError.ts

---

src/components/basics/VerticalTabSelector.tsx

fix dialog when mouse leaves the page

---

.github/dependabot.yml
.github/workflows/publish-wiki.yml

Add a dependabot configuration.
I did some grouping so there won't be too many PRs for version updates. The PRs could be merged on monday in a maintenance work.
There are too many updates to be done in one issue/pr so I am going to create subtasks and will activate automatic PRs when those dependencies are updated.
https://github.com/sirchnik-xitaso/mnestix-browser/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Aopen+author%3Aapp%2Fdependabot

chore(Dependabot): Add dependabot conf 

---

package.json
wiki/Keycloak-Configuration.md

Remove the dev port openings and live compiling from the docker scripts.
Fixes # (MNES-1519)

docs(dev-mode): Remove the dev from the keycloak readme and from the yarn scripts

---

.github/workflows/docker-build.yml
package.json
src/app/[locale]/viewer/_components/submodel-elements/generic-elements/entity-components/EntityTreeItem.tsx

**Fixes an issue where assets from the Bill of Materials (BoM) wouldn't open in Safari on iOS.**
This pull request includes a small change to the `EntityTreeItem.tsx` file. The change modifies the behavior of the `window.open` function to open the URL in the same tab instead of a new tab.
-   [ ] Safari (latest iOS version)
-   [ ] Google Chrome
-   [ ] Samsung Internet Browser
-   [ ] Mozilla Firefox
-   [ ] Google Chrome (Windows, macOS, Linux)
-   [ ] Mozilla Firefox
-   [ ] Microsoft Edge (Windows)
-   [ ] Safari (macOS)
-   [x] I have made corresponding …

HOT-FIX: fix(EntityTreeItem) - change window.open target to '_top' for assetId

---

src/app/[locale]/viewer/_components/submodel/carbon-footprint/visualization-components/ProductJourneyAddressList.tsx

don't show undefined for no country
Before:
After:

fix(product-journey):  don't show undefined for no country

---

compose.yml
wiki/Mnestix-Configuration-Settings.md

Removes the path to the logo in the compose.yml as there is no default logo in the data folder anymore. 
-   [ ] New and existing tests pass locally with my …

fix(theming): remove logo mounting in compose.yml

---

.vscode/settings.json
src/lib/api/configuration-shell-api/configurationShellApi.ts

BaSyx is giving a 404 if we use a PATCH Call in the ID Generation Settings and the value has not changed. To fix this for the user till BaSyx fixes this problem I excluded the 404 for this specific wrap to eliminate the error. I already made a ticket to reverse this change as soon as BaSyx will fix this.
-   [ ] I have made …

fix(IdGenerationSettings): Temporary Bugfix for BaSyx PATCH 404 error

---

src/app/[locale]/settings/_components/role-settings/RuleForm.spec.tsx
src/app/[locale]/settings/_components/role-settings/target-information/WildcardOrStringArrayInput.tsx

When the last id item gets removed, the wildcard is selected 
-   [ ] My changes contain no console …

fix(rbac-ui) app crashing when last id item gets removed

---

src/app/[locale]/settings/_components/role-settings/CreateRuleDialog.spec.tsx
src/app/[locale]/settings/_components/role-settings/CreateRuleDialog.tsx
src/app/[locale]/settings/_components/role-settings/RuleDialog.spec.tsx
src/app/[locale]/settings/_components/role-settings/RuleDialog.tsx
src/lib/services/rbac-service/RbacRulesService.spec.ts
src/lib/services/rbac-service/RbacRulesService.ts
src/locale/de.json
src/locale/en.json

Adds a notification for the error when creating a non unique idShort in create and update.
Fixes MNES-1647

fix(rbac): add error handling for unique idShort requirement

---

src/app/[locale]/settings/_components/role-settings/RuleForm.tsx
src/lib/services/rbac-service/RbacActions.ts
src/lib/services/rbac-service/RbacRulesService.spec.ts
src/lib/services/rbac-service/RbacRulesService.ts
src/locale/de.json
src/locale/en.json

add validation for role name length. This is not a BaSyx bug we have to ensure the name is not too long.
I added a check for spaces at the end too but that's just for easier use.
Fixes MNE-86

fix(rbac): add validation for role name length

---

src/app/[locale]/settings/_components/role-settings/CreateRuleDialog.spec.tsx
src/app/[locale]/settings/_components/role-settings/CreateRuleDialog.tsx
src/app/[locale]/settings/_components/role-settings/HintDialogContent.tsx
src/app/[locale]/settings/_components/role-settings/RuleDialog.spec.tsx
src/app/[locale]/settings/_components/role-settings/RuleDialog.tsx
src/locale/de.json
src/locale/en.json

A button. When the user clicks it, you are redirected to the used keycloak instance admin page.
Fixes # (MNE-114)

feat(rbac): show keycloak link in hint dialog

---

src/locale/en.json

Somehow the english texts for the product view got replaced by german strings. Reverted this change.

fix(localization)-fix english texts for product view

---

src/lib/api/infrastructure.ts

apiKey was overwritten by envs. Now the function call ApiKey has preference.
Fixes MNE-120

fix(transfer): apiKey can be used for the targetRepository

---

src/app/[locale]/product/[base64AasId]/page.tsx
src/app/[locale]/viewer/_components/submodel/sorting/SortNameplateElements.ts
src/lib/enums/SubmodelSemanticId.enum.ts
src/lib/services/list-service/ListService.ts

Introduce support for new Nameplate Semantic ID by updating the relevant enums and functions to include the new semantic ID.
As you can see here: https://industrialdigitaltwin.org/wp-content/uploads/2024/11/IDTA-02006-3-0_Submodel_Digital-Nameplate.pdf

fix(Nameplate): Add support for new Nameplate Semantic ID

---

.github/workflows/docker-build.yml

The only thing left from improving the release process. Now docs fixes or README fixes can be pushed to main without triggering pipelines.

chore: exclude docs from release trigger

---

src/app/[locale]/product/[base64AasId]/page.tsx
src/app/[locale]/viewer/[base64AasId]/page.tsx
src/app/[locale]/viewer/_components/SubmodelsOverviewCard.tsx
src/locale/de.json
src/locale/en.json
src/locale/es.json

This PR changes the visualization of the AAS when there is **no submodels** on that AAS.
Before the change, the card that showed the submodels did not appear, potentially producing the misconception that the submodels were loading still when the truth is that there is no submodels associated with that AAS.
Now, the card of the submodels appear and shows a message telling the user there are no submodels to load for that AAS, solving the potential misunderstanding.
It a**lso updates the Product page** so the behavior is consistent in viewer and in product pages.
-   [ ] New feature (non-breaking change which adds …

fix(SubmodelOverviewCard): AAS view with no submodels shows a message with that information

---

src/app/[locale]/viewer/_components/submodel/SubmodelDetail.spec.tsx
src/app/[locale]/viewer/_components/submodel/SubmodelDetail.tsx
src/lib/util/SubmodelResolverUtil.ts

This PR includes code to look for a submodel visualization when the `semanticId?.keys` contains more than 1 key in position [0]. So a special visualization can be recovered if available for the submodel. To this end:
- Generic function `findSemanticIdInMap` added to `submodelResolverUtils`. This function can be reused to find the semantic id key of any map (future potential use to replace all the `submodel?.semanticId?.keys?[0].value` statements that only check the first entry of the semanticId keys.
- Uses this function to recover submodel visualization in `SubmodelDetail.ts`.
- Implemented a new test for `SubmodelDetail` to check that it identifies the correct visualization even when more than 1 semanticId key,
-   [ ] Minor change …

fix(submodelDetail): find submodelVisualization when more than 1 semanticId

---

src/app/[locale]/marketplace/catalog/_components/EClassFilter.tsx
src/app/[locale]/marketplace/catalog/page.tsx
src/locale/de.json
src/locale/en.json
src/locale/es.json

removed eclass hierarchy from filter and added link to the documentation
filter box is not shown when there are no filters
-   [ ] New and existing tests pass …

removed eclass hierarchy and show link to documentation instead

---

src/app/[locale]/product/[base64AasId]/page.tsx

This pull request includes a minor change to the `Page` component in `src/app/[locale]/product/[base64AasId]/page.tsx`. The change reorders the call to `setIsBreadcrumbsLoading(false)` to ensure it is executed after `setBreadcrumbLinks` for better readability and logical flow. ([src/app/[locale]/product/[base64AasId]/page.tsxL164-R167](diffhunk://#diff-ccee45e0b50344c81e3a4f06db382e7df1442951aac8bcc0148354cdd5cfe882L164-R167))

fix(Page): ensure breadcrumbs loading state is updated correctly

---

src/layout/Footer.tsx
src/locale/de.json
src/locale/en.json
src/locale/es.json

This pull request adds a "Documentation" link to the footer of the application, along with localization support for the new label. The most important changes include defining the documentation URL, updating the footer layout to include the link, and adding translations for the "Documentation" label in multiple languages.
* [`src/layout/Footer.tsx`](diffhunk://#diff-572eafd1fd6871371a8db00a253950c22004d3c69d83a7fa568e76aee48d9b5eR18): Added a `documentationURL` constant and updated the footer layout to include a "Documentation" link pointing to the specified URL. The link opens in a new tab. [[1]](diffhunk://#diff-572eafd1fd6871371a8db00a253950c22004d3c69d83a7fa568e76aee48d9b5eR18) [[2]](diffhunk://#diff-572eafd1fd6871371a8db00a253950c22004d3c69d83a7fa568e76aee48d9b5eR86-R95)
* …

feat(Footer): add documentation link to footer

---

src/app/[locale]/product/_components/ProductOverviewCard.tsx

This pull request introduces a small change to the `ProductOverviewCard` component to enhance security and functionality when navigating to a product URL. The change ensures that the product URL is opened in a new tab with secure attributes (`noopener` and `noreferrer`).

feat(ProductOverviewCard): open product URL in a new tab when navigating

---

src/app/[locale]/marketplace/_components/manufacturerCard.tsx
src/app/[locale]/marketplace/catalog/_components/FilterContainer.tsx
src/app/[locale]/marketplace/catalog/page.tsx
src/lib/api/graphql/catalogActions.ts
src/locale/de.json
src/locale/en.json
src/locale/es.json

* `src/app/[locale]/marketplace/_components/manufacturerCard.tsx`: Replaced the placeholder article count logic with an asynchronous fetch using `searchProducts`. Added loading and error states to display a spinner or fallback text when the product count is unavailable.
* [`src/lib/api/graphql/catalogActions.ts`](diffhunk://#diff-c1ee46582e7df854f1bed244ae6ca520778a5ce9f4d314a78dc6780773200e61L67-R70): Modified the `searchProducts` function to accept `aasSearcherUrl` as the first parameter and `filters` as the second, improving parameter clarity and usage consistency.
* Added a new translation key `articleCountUnavailable` to indicate when filtering is not configured, with updates to `de.json`, `en.json`, and `es.json` to support German, English, and Spanish translations. …

feat(manufacturerCard): Add filterable Aas count

---

src/app/[locale]/marketplace/catalog/_components/FilterContainer.tsx
src/app/[locale]/marketplace/catalog/_components/ProductCategoryFilter.tsx
src/lib/api/graphql/catalogActions.ts

This pull request updates the `ProductCategoryFilter` component to enhance the filtering logic by introducing a `rootName` parameter. This parameter ensures that checkbox state updates are scoped to the relevant product root, improving the accuracy of filter interactions.
* `updateActiveFilters` function: Added an optional `rootName` parameter to refine the filtering logic. The function now verifies if the selected family or designation matches the specified root name before updating the filter state. 
* `updateCheckboxState` function: Updated to accept the `rootName` parameter and pass it to the `updateActiveFilters` function, ensuring that filter updates are scoped to the correct product root. 
* Checkbox event handler for `productFamily`: Modified to pass the …

fix(filter-select): verify if correct family root is selected

---

.github/CODEOWNERS
docker-compose/compose.proxy.yml
package.json
src/app/[locale]/marketplace/catalog/_components/FilterContainer.tsx
src/app/[locale]/marketplace/catalog/_components/ProductCategoryFilter.tsx
src/app/[locale]/settings/_components/role-settings/CreateRuleDialog.spec.tsx
src/app/[locale]/settings/_components/role-settings/CreateRuleDialog.tsx
src/app/[locale]/settings/_components/role-settings/DeleteRoleDialog.tsx
src/app/[locale]/settings/_components/role-settings/DeleteRuleDialogContent.tsx
src/app/[locale]/settings/_components/role-settings/FormMappingHelper.spec.ts
src/app/[locale]/settings/_components/role-settings/FormMappingHelper.ts
src/app/[locale]/settings/_components/role-settings/RoleAccordion.tsx
src/app/[locale]/settings/_components/role-settings/RoleActionMenu.spec.tsx
src/app/[locale]/settings/_components/role-settings/RoleActionMenu.tsx
src/app/[locale]/settings/_components/role-settings/RuleDialog.spec.tsx
src/app/[locale]/settings/_components/role-settings/RuleDialog.tsx
src/app/[locale]/settings/_components/role-settings/RuleForm.spec.tsx
src/app/[locale]/settings/_components/role-settings/RuleForm.tsx
src/app/[locale]/settings/_components/role-settings/RuleSettings.tsx
src/app/[locale]/settings/_components/role-settings/test-data/mockRbacRoles.ts
src/lib/api/graphql/catalogActions.ts
src/lib/services/rbac-service/RbacRulesService.spec.ts
src/lib/services/rbac-service/RbacRulesService.ts
src/lib/services/rbac-service/types/RbacServiceData.ts
src/locale/de.json
src/locale/en.json
src/locale/es.json
wiki/Getting-Started-with-Developing.md

This pull request introduces changes to improve role-based access control (RBAC) functionality, enhance user interface elements, and update localization files. 
* Added a `selectedRole` property to `RoleDialogProps` in `CreateRuleDialog` and `RuleForm`, allowing pre-selection of roles during permission creation. Updated the default values and logic in `RuleForm` to handle this new property. 
* Updated `RuleSettings` to manage the `selectedRole` state and pass it to child components, ensuring seamless integration of the pre-selected role feature.
* Added an "Add Permission" button to the `RoleAccordion` component, enabling users to quickly add permissions to roles. Updated layout and styling to accommodate the new button. 
* Revised translations in `de.json`, `en.json`, and `es.json` to …

style(rbac): adjustments for rule naming and creation

---

src/app/[locale]/list/_components/AasListTableRow.tsx

This pull request introduces error handling to the `translateListText` function in the `AasListTableRow` component to handle edge cases where the input might not conform to the expected type.
* `src/app/[locale]/list/_components/AasListTableRow.tsx`: Updated the `translateListText` function to include a `try-catch` block. This ensures that if the `property` is not of the expected `MultiLanguageValueOnly` type or an error occurs, it handles the scenario by either returning the string directly (if the property is a string) or logging an error and returning an empty string. 
-   [ ] New feature …

fix(AasList)-handle-incorrect-MLP

---

.github/workflows/docker-build.yml
compose.yml
package.json

This pull request updates the version of the `mnestix-browser` application from `1.5.2` to `1.6.0` across multiple files to ensure consistency in the versioning.
* [`.github/workflows/docker-build.yml`](diffhunk://#diff-3414847e2ad632333f775cabb810f0dc0df61a570365df34750a08b00912fe82L30-R30): Updated the `IMAGE_TAG_VERSION` environment variable to `1.6.0` to reflect the new version in the Docker build workflow.
* [`compose.yml`](diffhunk://#diff-3493e6b5ddf34891e572f911db893efd9e46af828e011ea778a7c1eb64763588L13-R13): Updated the Docker image version for the `mnestix-browser` service to `1.6.0` in the `volumes:` section.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Updated the `version` field to `1.6.0` to align with the new …

Chore(release): Bump version to 1.6

---

.dockerignore
Dockerfile
scripts/start.sh

This pull request updates the Docker and startup workflow to improve Prisma database handling and ensure migrations are applied correctly during deployment. The main changes focus on making database setup more robust and simplifying how the Prisma client and database files are managed in the build process.
**Database setup and migration improvements:**
* In `Dockerfile`, added a step to run `yarn prisma migrate deploy` and `yarn prisma generate` during the build to ensure the database schema and Prisma client are prepared before packaging the app.
* Updated the production image to install the `prisma` package at runtime, ensuring migration commands are available in the final container.
* Changed how Prisma files are copied into the production image: now the entire `prisma` directory is …

fix(prisma): Add prisma database mitigation to startup

---

src/lib/services/concept-description-service/ConceptDescriptionRepositoryService.spec.ts
src/lib/services/concept-description-service/ConceptDescriptionRepositoryService.ts
src/lib/services/concept-description-service/conceptDescriptionRepositoryActions.ts

This pull request refactors the way concept descriptions are fetched by ID from repositories, focusing on improving clarity and reliability when querying by infrastructure. The main changes include renaming methods for better intent, updating the logic to fetch from multiple repository URLs within an infrastructure, and strengthening error handling when infrastructure information is missing or incorrect.
**Refactoring and API improvements:**
* Renamed methods in `ConceptDescriptionRepositoryService` for clarity, replacing `getConceptDescriptionByIdFromRepositories` with `getConceptDescriptionByIdFromInfrastructure`, and reorganized the logic to fetch from all relevant repository URLs within the specified infrastructure.
* Added new helper methods: …

chore: Cleanup Concept Description Service
