eclipse-mnestix/mnestix-browser

src/app/[locale]/viewer/_components/submodel/carbon-footprint/visualization-components/CO2Equivalents.spec.tsx
src/app/[locale]/viewer/_components/submodel/carbon-footprint/visualization-components/CO2Equivalents.tsx

Added component tests to verify that the total CO2 Equivalents are displayed correctly
Fixes # (MNES-1365)

test(CarbonFootprintSubmodel): Add tests for CO2 Equivalent View

---

README.md

docs(ReadMe):Updated ReadMe to new Repository

---

src/app/[locale]/list/_components/AasListDataWrapper.spec.tsx
src/app/[locale]/list/_components/AasListDataWrapper.tsx
src/app/[locale]/list/_components/AasListHeader.tsx
src/app/[locale]/list/_components/filter/SelectRepository.spec.tsx
src/app/[locale]/list/_components/filter/SelectRepository.tsx
src/test-utils/CustomRender.tsx

Component Tests for AASListDataWrapper.tsx and RepositorySelect.tsx

feat(aas list): UI tests

---

src/app/[locale]/viewer/_components/submodel/carbon-footprint/visualization-components/ProductLifecycle.spec.tsx
src/app/[locale]/viewer/_components/submodel/carbon-footprint/visualization-components/ProductLifecycle.tsx

added component test for Product lifecycle

test(CarbonFootprintVisualizations): write test for ProductLifecycle

---

src/app/[locale]/list/_components/AasList.tsx
src/app/[locale]/list/_components/AasListTableRow.tsx
src/lib/util/ToolTipText.tsx

feat(aas-list): seperate asset ID and AAS ID columns

---

src/app/[locale]/list/_components/AasList.tsx
src/app/[locale]/list/_components/AasListDataWrapper.spec.tsx
src/app/[locale]/list/_components/AasListDataWrapper.tsx
src/app/[locale]/list/_components/AasListTableRow.tsx
src/locale/de.json
src/locale/en.json

Thumbnail gets fetched from the selected repository.
If there is no default repository, the user has to select a repository from the select before we load the list.

Feat(aas list) adapt thumbnail url

---

src/app/[locale]/viewer/_components/submodel-elements/document-component/DocumentComponent.tsx
src/lib/services/search-actions/searchActions.ts

The check if a document attachment is available is now performed on the server side.
Fixes # (MNES-1349)

Fix(document): document check now performed on server side

---

src/global.d.ts
src/i18n.ts
src/user-plugins/locale/en.json
src/user-plugins/submodels/README.md
src/user-plugins/submodels/hello-world/HelloWorldComponent.tsx

Suggestion for how to make localization usable in the user-plugins.
-   [ ] My changes contain no …

Added possibility to add localization to custom sm visualization

---

docker-compose/data/keycloak/Dockerfile

Chore(keycloak dockerfile): added platform tag for arm users

---

src/layout/Footer.tsx
src/layout/LayoutRoot.tsx
src/layout/menu/MainMenu.tsx

Created footer with copyright, imprint and data privacy

Feat(mnestix related infos footer)

---

compose.frontend.yml
docker-compose/compose.frontend.yml
src/app/[locale]/settings/page.tsx
src/app/env/env.ts
src/layout/menu/MainMenu.tsx

bugfix(docker compose): add docker compose without mnestix api

---

src/app/[locale]/viewer/_components/submodel-elements/SubmodelElementCustomVisualizationMap.ts
src/app/[locale]/viewer/_components/submodel/SubmodelCustomVisualizationMap.ts

docs(custom-submodel-visualization):add docstrings to mappings

---

README.md
docker-compose/compose.frontend.yml

chore(README): Update Readme for Mnestix docker compose.frontend

---

.github/workflows/docker-build.yml
compose.yml
package.json

Increase version 1.3.2 -> 1.3.3

version 1.3.3

---

src/authConfig.ts

Fixed automated refresh of the Azure AD authentication token, if it is expired. (No more errors after waiting in the list <3) …

Bugfix(authentication): Refresh AuthToken for Azure AD

---

src/app/[locale]/_components/DashboardInput.tsx
src/app/[locale]/_components/ManualAasInput.tsx
src/app/[locale]/asset/_components/RedirectToViewer.tsx
src/app/[locale]/compare/_components/CompareSubmodelElement.tsx
src/app/[locale]/compare/_components/CompareView.tsx
src/app/[locale]/compare/_components/add-aas/AddAasToCompareCard.tsx
src/app/[locale]/compare/_components/add-aas/CompareAasAddDialog.tsx
src/app/[locale]/compare/_components/add-aas/CompareRecordCollectionRow.tsx
src/app/[locale]/templates/_components/template-edit/TemplateEditFields.tsx
src/app/[locale]/viewer/[base64AasId]/page.tsx
src/app/[locale]/viewer/_components/submodel-elements/generic-elements/GenericSubmodelElementComponent.tsx
src/lib/hooks/UseShowError.tsx
src/lib/i18n/de.mnestix.ts
src/lib/i18n/en.mnestix.ts
src/locale/de.json
src/locale/en.json

I had free time and did not want to start a new ticket.
Compare view and more of the dashboard now use next-intl

Chore(translations) change some translations to next intl

---

docker-compose/data/keycloak/realm/BaSyx-realm.json

Keycloak default development setup
- Included 'mnestix-admin' as a default role for 'test' user
- …

feat(Keycloak_Realm): add 'mnestix-admin' role as default setup

---

src/components/authentication/authConfig.ts
src/lib/hooks/UseAuth.ts

mnestix-admin role works now in azure entra id

Feat(rbac) azure entra

---

src/app/[locale]/viewer/_components/submodel/SubmodelInfoDialog.tsx
src/components/basics/VerticalTabSelector.tsx

Fixed info icon so the active submodel tab always shows the info icon.
Also Dialog information is now shown for the right submodel

bugfix(submodel-view): change visibility of info dialog icon and show the right information in the dialog window

---

.github/workflows/publish-wiki.yml
wiki/Contributing.md
wiki/Docker-Compose-Files.md
wiki/Feature-Overview.md
wiki/Getting-Started-with-Developing.md
wiki/Home.md
wiki/How-to-Create-Custom-Submodel-Visualizations.md
wiki/Keycloak-Configuration.md
wiki/Maintaining.md
wiki/Mnestix-Configuration-Settings.md
wiki/Secret-Environment-Variables.md
wiki/Use-Mnestix.md
wiki/_Sidebar.md
wiki/home.md

Add wiki sync in one direction from repo to wiki.
From now on just changes inside the IDE inside the folder wiki and not in the GitHub GUI

docu(wiki): Add wiki sync from repo to wiki on GitHub

---

src/app/[locale]/viewer/_components/SubmodelsOverviewCard.tsx
src/components/basics/VerticalTabSelector.tsx
src/locale/de.json
src/locale/en.json

Added translation to tooltip when there is an error while loading a submodel

Chore(submodel tooltip):rework the tooltip

---

.github/workflows/docker-build.yml
compose.yml
package.json

Chore(increase verison) Increased Version to 1.4.0

---

src/components/authentication/authConfig.ts

load user-name from access-token when using azure entra id

fix show user name when logged in with entra id

---

.github/workflows/docker-build.yml

Fix copy-pasta :spaghetti: with DOCKER_API_TOKEN of #90

ci(docker-login): fix docker login

---

src/lib/services/repository-access/RepositorySearchService.ts

fix(submodel-bom):fix fetch of submodel refs

---

.github/workflows/docker-build.yml

fixing cache fight which results in auth fail# Description
A try to fix merges to staging

ci: only run on branch not on pr and branch

---

.github/workflows/docker-build.yml

Another try to fix the image push for release

ci: cache images manually

---

src/components/basics/AboutDialog.tsx
src/layout/Footer.tsx

Styling of Footer.
Use of Grid instead of NavigationBar, as it is used in a different context.

chore(footer): Fix styling of Footer

---

wiki/Mnestix_API_Documentation.md
wiki/_Sidebar.md

Updating the links so that the documentation works :D

Update Links and Info notes

---

README.md
wiki/Mnestix_API_Data_Ingest.md
wiki/Mnestix_API_Documentation.md
wiki/_Sidebar.md
wiki/mnestix-api.compose.yaml

* Test Register Newsletter
* Update
* Add Data Ingest Documentation
* Update links to point to eclipse Mnestix2
* Update Mnestix_API_Data_Ingest.md
* Create mnestix-api.compose.yaml
* Update Mnestix_API_Documentation.md
---------
-   [ ] I have commented my code, …

main to dev (#128)

---

src/middleware.ts

Add a 404 redirect for comparision and list if feature is deactivated
-   [ *] Bug fix (non-breaking change which fixes an issue)
-   [ ] My …

bugfix(comparision, list): Add 404 redirect if feature is disabled

---

.github/workflows/docker-build.yml
package.json
src/app/[locale]/viewer/_components/submodel-elements/generic-elements/entity-components/EntityTreeItem.tsx

Sync main to dev

---

src/app/[locale]/viewer/_components/submodel-elements/generic-elements/entity-components/EntityTreeItem.tsx

Should have waited for the linting check...

fix(linting): Replace weird whitespace with normal space

---

.github/CODEOWNERS

Add Milo and me.
I know this will only work after the next release when it is on default.

chore: upate codeowners

---

src/locale/de.json
src/locale/en.json

Chore(language fix):fix translation errors

---

src/app/[locale]/templates/[id]/page.tsx
src/lib/i18n/de.mnestix.ts
src/lib/i18n/en.mnestix.ts

Add a button to copy the template ID in the template builder
-   [x] I have performed a self-review of my codex

Add a button to copy the template ID in the template builder

---

compose.yml

Update the API version in the docker compose file to run the newest version. Important for testing. …

chore(API-version)Update compose.yml to API 1.3.2

---

.github/CODEOWNERS

Remove Milos old account to avoid someone taking the username :)

Remove Milos old account from CODEOWNERS

---

.github/workflows/docker-build.yml
.github/workflows/publish-wiki.yml

chore: fix codeql workflow error
See Issue for other dismissal reasons.
https://xitaso.atlassian.net/browse/MNES-1614?focusedCommentId=87083

chore: fix codeql workflow error

---

src/app/[locale]/settings/_components/role-settings/FormMappingHelper.spec.ts
src/app/[locale]/settings/_components/role-settings/FormMappingHelper.ts
src/app/[locale]/settings/_components/role-settings/RoleDialog.spec.tsx
src/app/[locale]/settings/_components/role-settings/RoleDialog.tsx
src/app/[locale]/settings/_components/role-settings/RoleDialogForm.tsx
src/app/[locale]/settings/_components/role-settings/RoleForm.tsx
src/app/[locale]/settings/_components/role-settings/RoleSettings.spec.tsx
src/app/[locale]/settings/_components/role-settings/RoleSettings.tsx
src/app/[locale]/settings/_components/role-settings/target-information/TargetInformationForm.tsx
src/app/[locale]/settings/_components/role-settings/target-information/TargetInformationView.tsx
src/app/[locale]/settings/_components/role-settings/target-information/WildcardOrStringArrayInput.tsx

type can now be edited in the dialog
added first component tests for: table, dialog, helper
-   [ ] …

Feat(rbac UI)component tests for view logic

---

src/locale/de.json

fix(german-translations): change acronyms and fix some grammar

---

docker-compose/data/keycloak/sec_sm_roles.json

Added the 'security-admin' role to the security repo, so you can get access to that repo and not be basyx-admin for everything else

chore(RBAC): add security admin role

---

.env.local

Added the product view env to .env.local

chore(envs):add product view feature flag to environment variables

---

src/app/[locale]/product/[base64AasId]/page.tsx
src/app/[locale]/viewer/_components/submodel/generic-submodel/GenericSubmodelDetailComponent.tsx

Hide nameplate, VEC-SML and numberOfDocuments

feat(polish-product-view):hide nameplate and numberOfDocuments

---

src/app/[locale]/viewer/_components/SubmodelsOverviewCard.tsx
src/app/[locale]/viewer/_components/submodel/SubmodelInfoDialog.tsx
src/app/[locale]/viewer/_components/submodel/technical-data/ConceptDescriptionHelper.ts
src/app/[locale]/viewer/_components/submodel/technical-data/DataRowWithUnit.tsx
src/app/[locale]/viewer/_components/submodel/technical-data/TechnicalDataDetail.tsx
src/app/[locale]/viewer/_components/submodel/technical-data/TechnicalDataElement.tsx
src/locale/de.json
src/locale/en.json

Fallback to generic view if data can't be rendered.

Feat(technical data) fallback to generic view

---

src/app/[locale]/viewer/_components/submodel/technical-data/ConceptDescriptionHelper.ts
src/app/[locale]/viewer/_components/submodel/technical-data/DataRowWithUnit.tsx

Show symbol from concept description if available.

fix(concept-description)-show symbol if available

---

src/middleware.ts

Add middleware for product feature flag (to keep upcoming release clean)
-   [ ] My …

fix(middleware): add 404 redirection for product view feature flag

---

.github/workflows/docker-build.yml
compose.yml
package.json
src/app/[locale]/settings/_components/mnestix-connections/MnestixConnectionsCard.tsx
src/app/[locale]/settings/_components/role-settings/RuleForm.tsx
src/app/[locale]/viewer/_components/submodel-elements/document-component/DocumentComponent.tsx
src/lib/services/search-actions/searchActions.ts

Release version 1.5.0
Fixes # (MNE-85)

chore(release): bugs during testing and version increase to 1.5.0

---

src/app/[locale]/product/_components/ProductActionMenu.tsx
src/app/[locale]/product/_components/ProductClassificationInfoBox.tsx
src/app/[locale]/product/_components/ProductOverviewCard.tsx

If there is no valid classification in keyfacts => keyfacts are not shown
Fixed one styling problem in product view
-   [ ] New and existing tests pass locally …

refactor(product): clean up classification filtering and improve layout

---

src/i18n/routing.ts
src/locale/es.json
src/user-plugins/locale/es.json

This PR adds Spanish language support to Mnestix browser. Follows the current language selection mechanism (change in url)
-   [ ] New and existing tests pass …

feat(locale): add spanish language support

---

docker-compose/compose.searcher.yml

added compose file to start the mnestix-searcher service with a mongoDB

Feat(aas searcher) add mnestix-searcher and mongodb compse.yml

---

src/app/[locale]/product/_components/ProductActionMenu.tsx
src/app/[locale]/product/_components/ProductOverviewCard.tsx
src/lib/api/basyx-v3/api.ts
src/lib/services/repository-access/repositorySearchActions.ts
src/locale/de.json
src/locale/en.json
src/locale/es.json

Add Download Button to Action Menu in Product View. 
Please check Spanish translation.
-   [ ] New and existing tests pass locally with my …

feat(aasx-download): Add aasx download button for product view to action menu

---

src/app/[locale]/viewer/_components/submodel/carbon-footprint/visualization-components/CO2EDistributionDiagrams/CO2EDistributionBarchart.spec.tsx
src/locale/de.json
src/locale/en.json
src/locale/es.json
wiki/Adding-Languages.md

This PR updates the languages english and spanish to fit language guidelines and [carbon sentence-case](https://carbondesignsystem.com/guidelines/content/writing-style/) to enhance consistency along languages.
Also, it updates the documentation regarding languages, adding the conventions we are following regarding the languages and referencing the sentence-case style.
-   [ ] I have commented my code, …

chore(locale): update languages format

---

docker-compose/compose.searcher.yml
src/app/[locale]/marketplace/catalog/_components/EClassFilter.tsx
src/app/[locale]/marketplace/catalog/_components/FilterContainer.tsx
src/app/[locale]/marketplace/catalog/_components/ProductCategoryFilter.tsx
src/app/[locale]/marketplace/catalog/_components/VecFilter.tsx
src/app/[locale]/marketplace/catalog/page.tsx
src/app/[locale]/marketplace/page.tsx
src/lib/api/graphql/apolloClient.ts
src/lib/api/graphql/catalogActions.ts
src/locale/de.json
src/locale/en.json
src/locale/es.json

This pull request introduces several significant changes to enhance functionality and improve code organization across multiple components. Key updates include the addition of dynamic filtering capabilities, integration of asynchronous data fetching, and improvements to the user interface for filtering product categories. Changes are grouped into themes for clarity.
* **`src/app/[locale]/marketplace/catalog/_components/EClassFilter.tsx`**: Added a `useEffect` hook to dynamically update parent components when filter states change. Improved handling of group filters by introducing indeterminate state for checkboxes. 
* **`src/app/[locale]/marketplace/catalog/_components/VecFilter.tsx`**: Incorporated `useEffect` to synchronize selected filters with parent components dynamically. Simplified …

feat(filter options): Add fetch filter options from API

---

src/app/[locale]/marketplace/catalog/page.tsx
src/app/[locale]/marketplace/page.tsx
src/locale/de.json
src/locale/en.json
src/locale/es.json

This pull request introduces changes to enhance the marketplace pages by adding a disabled search field, repositioning the chatbot button, and updating localization files with a new placeholder text for the search field. Below is a summary of the most important changes grouped by theme.
* Added a disabled `TextField` with a placeholder for search functionality in the `marketplace/catalog/page.tsx`. The search field includes a `SearchIcon` as a start adornment and is styled with specific width and margin properties. ([src/app/[locale]/marketplace/catalog/page.tsxL77-R95](diffhunk://#diff-4b9a19d210fbecbf939897b1b408869fec643ac6b8db1668d66b182288c39e70L77-R95))
* Repositioned the chatbot button in `marketplace/page.tsx` to a fixed position at the bottom-right corner of the page for improved …

feat(marketplace): add search bar

---

.github/dependabot.yml

As discussed in the daily this updates dependabot to do biweekly and monthly updates.

chore(deps): update dependabot to do biweekly and monthly

---

.github/actions/setup-build/action.yml
.github/workflows/docker-build.yml
src/lib/services/database/PrismaConnectorInMemory.ts

This pull request introduces a new GitHub action for setting up the build environment, updates the CI workflow to support a new feature branch, and makes adjustments to Docker image tagging. Additionally, a placeholder method has been added to the in-memory Prisma connector. Below is a breakdown of the most important changes:
* Added a new composite action `Setup Build Environment` in `.github/actions/setup-build/action.yml` to streamline the build process by restoring caches, setting up QEMU and Docker Buildx, and logging into DockerHub.
* Updated `.github/workflows/docker-build.yml` to include the new feature branch `feat(configurable-catalog` in both `push` and `pull_request` triggers. [[1]](diffhunk://#diff-3414847e2ad632333f775cabb810f0dc0df61a570365df34750a08b00912fe82L5-R5) …

feat(ci/cd)- add composite action to push product image

---

docker-compose/dynamic-rbac/initial-submodel.json

Auto generated rules for initial submodel update. 
-   [ ] My changes contain no …

fix(RBAC) - initial submodel update

---

src/app/[locale]/marketplace/catalog/_components/EClassFilter.tsx
src/app/[locale]/marketplace/catalog/_components/FilterContainer.tsx
src/app/[locale]/marketplace/catalog/_components/ProductCategoryFilter.tsx
src/app/[locale]/marketplace/catalog/_components/VecFilter.tsx
src/app/[locale]/settings/_components/mnestix-connections/MnestixConnectionGroupForm.tsx
src/locale/de.json
src/locale/en.json
src/locale/es.json

Review Feedback for filter and settings

Feat(configurable catalog) feedback

---

Dockerfile
src/app/EnvProvider.tsx
src/layout/menu/MainMenu.tsx
src/lib/env/MnestixEnv.ts
src/lib/util/RandomUtils.ts

This pull request introduces functionality to display the build timestamp in the application, including backend support for setting the timestamp during the build process and frontend updates to display it in the UI. The most important changes include adding a build timestamp to the Docker image, exposing the `BUILD_DATETIME` environment variable to the client, and formatting and displaying the timestamp in the main menu.
* **Dockerfile**: Added a step to generate a `BUILD_DATETIME` timestamp during the build process and append it to the `.env` file.
* **`src/lib/env/MnestixEnv.ts`**: Introduced `cfgBuildEnvs` to map the `BUILD_DATETIME` environment variable and included it in `publicEnvs` for client-side access. 
* **`src/layout/menu/MainMenu.tsx`**: 
- Imported `formatTimestamp` utility …

feat(version): add buildtime to version in frontend

---

src/app/[locale]/marketplace/catalog/page.tsx
src/locale/de.json
src/locale/en.json
src/locale/es.json

This pull request introduces a search functionality to the marketplace catalog page, allowing users to filter products based on their names or designations. It also includes minor improvements to localization strings and code formatting.
* Added a `searchText` state to track the user's input and a `handleSearch` function to update it. 
* Implemented a `filteredProducts` variable using `useMemo` to filter products based on the search text, matching either the manufacturer name or product designation. 
* Updated the `ProductList` component to use `filteredProducts` instead of the original `products`. 
* Enabled the search input field, connected it to the `searchText` state, and styled it appropriately. 
* Updated the `searchPlaceholder` text in the German, English, and Spanish localization …

feat(product-list): minimal search box

---

.github/workflows/docker-build.yml
src/app/[locale]/product/[base64AasId]/page.tsx
src/app/[locale]/product/_components/CommercialDataBox.tsx
src/app/[locale]/product/_components/ProductOverviewCard.tsx
src/locale/de.json
src/locale/en.json
src/locale/es.json

Feat(commercial data)

---

src/lib/api/graphql/catalogActions.ts

Fix(filter) unknown root

---

wiki/product-catalog.md

added more documentation about the catalog

---

docker-compose/compose.proxy.yml

Extracted this change from another PR to not interfere with the maintenance branch.
Updates the proxy compose image to use the most recent dev image.

fix(compose): Update the proxy image

---

README.md

Updates the link to our demonstration instance.

chore: Update README link

---

wiki/Home.md

sorry I just checked again and we also had it in our wiki

chore: update demo link also in wiki

---

package.json
src/app/[locale]/viewer/_components/submodel-elements/document-component/DocumentUtils.ts
src/lib/api/infrastructure.ts
src/lib/services/fileActions.ts

fix document loading with rbac

---

wiki/Feature-Overview.md

This pull request updates the `Feature-Overview.md` documentation to include a detailed explanation of the Mnestix Browser Asset ID resolving feature, along with examples of implementation solutions.
* **Added section on Mnestix Browser Asset ID Resolving**: Describes the automatic resolving of Asset IDs via the Main Landing Page or server forwarding, with use cases such as QR Code generation for showcases. Includes an illustrative image and implementation details.
* **Solution 1 - HTML Redirect**: Provides an example of a simple HTML file with JavaScript for redirecting users to the correct Mnestix instance.
* **Solution 2 - Proxy Redirect**: Includes a Caddyfile example for implementing a proxy-based HTTP redirect response.

docs: update for /asset endpoint

---

.github/workflows/docker-build.yml
compose.yml
package.json

Update version 1.5.1 to 1.5.2

---

package.json
yarn.lock

We no longer use zod -> removed it from the dependencies

removed unused package zod

---

.vscode/launch.json
docker-compose/compose.dynamic-rbac-proxy.yml
docker-compose/compose.dynamic-rbac.yml
docker-compose/compose.proxy.yml
src/lib/api/configuration-shell-api/configurationShellApiV2.ts
src/lib/api/infrastructure.ts
src/lib/api/template-shell-api/templateShellApi.ts
src/lib/env/MnestixEnv.ts
src/lib/services/configurationApiActions.ts
wiki/Mnestix-Configuration-Settings.md

This pull request introduces changes to support a new version of the Mnestix API (v2) while maintaining compatibility with the existing API. Key updates include adjustments to environment configurations, API endpoints, and the introduction of a new `ConfigurationShellApiV2` class. Additionally, there are refinements to Docker Compose configurations to better handle dynamic RBAC and proxy setups.
* Introduced a new `ConfigurationShellApiV2` class to support Mnestix API v2, with methods for handling ID generation settings and submodel elements.
* Modified `configurationApiActions` to dynamically select between `ConfigurationShellApi` and `ConfigurationShellApiV2` based on the `MNESTIX_V2_ENABLED` flag. 
* Added a new `MNESTIX_V2_ENABLED` environment variable to toggle between API versions. …

Feat(proxy): Support for v2 Mnestix API - Feature Flag

---

cypress/e2e/a_billOfMaterial.spec.js
cypress/e2e/templateTest.spec.js
package.json
src/app/[locale]/templates/[id]/page.tsx
src/app/[locale]/templates/_components/template-edit/TemplateEditTree.tsx
src/app/[locale]/templates/_components/template-edit/TemplateEditTreeItem.tsx
src/app/[locale]/templates/_components/template-edit/TemplateEditTreeItemMenu.tsx
src/app/[locale]/viewer/_components/submodel-elements/generic-elements/entity-components/EntityTreeItem.tsx
src/app/[locale]/viewer/_components/submodel-elements/generic-elements/entity-components/TreeItem.tsx
src/app/[locale]/viewer/_components/submodel/bill-of-applications/visualization-components/ApplicationTreeItem.tsx
src/app/[locale]/viewer/_components/transfer/TargetRepositories.tsx
yarn.lock

Adapted all usages of TreeView to work with the latest mui-x version.

Chore(mui deprecations)

---

src/app/[locale]/viewer/_components/submodel/bill-of-applications/visualization-components/ApplicationTreeItem.tsx

Fix padding of Tree Components

fix styling

---

docker-compose/compose.keycloak.yml

Fix(compose) keycloak

---

docker-compose/compose.dynamic-rbac-proxy.yml
docker-compose/compose.dynamic-rbac.yml

fix(compose): proxy keycloak
